### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by yueliuLEE** [snakem982/Pandora-Box#1]
大佬,感谢你开发这个软件,使用下来有些问题不知道怎么解决.
1.就是这个软件的配置文件在什么地方,我找了但是没找到.
2.这个代理软件的默认代理模式是什么,我启动后某些国外网站无法访问,看日志信息是被默认拦截了,但是按照配置文件的话应该是走的代理节点.
3.代理端口能否设置为固定端口,因为每次启动时代理端口都会变,使用起来不太方便.
最后非常感谢大佬写了这个简单好用的代理软件

**Comment by snakem982** [comment]
1、配置文件在根目录Pandora-Box文件夹下
2、默认rule模式且不支持修改，什么网站？无论啥规则都默认拦截一些有小电影的网站！！！
      如果你认为那个网站内容无伤大雅，写到issues里下个版本放行
3、代理端口可以在通用设置，设置了就是固定的了

**Comment by yueliuLEE** [comment]
哦,是这样啊,谢谢大佬,网站是这个泥视频:https://www.nivod4.tv/index.html,

**Comment by snakem982** [comment]
> 哦,是这样啊,谢谢大佬,网站是这个泥视频:https://www.nivod4.tv/index.html,

嘻嘻，这个网站是有小电影的，为了山区孩子的身心健康不能放开

**Comment by snakem982** [comment]
> 大佬,代理端口我设置后,但是每次重新启动就又会改变

目前这个版本确实存在问题，在下个版本之前可以这样操作
在系统代理打开的情况下设置代理端口，软件关闭时不要关闭系统代理
下次打开软件就是固定的了
<img width="723" alt="代理" src="https://github.com/snakem982/Pandora-Box/assets/127644738/39878308-e204-41ec-8e58-6d0e12193755">

**Comment by yueliuLEE** [comment]
哦哦,好的,感谢大佬!
