### ISSUE TITLE
windows 0.2.9 版本，还是无法订阅，订阅解析失败

### ISSUE THREAD

**Issue by superiorzero** [snakem982/Pandora-Box#11]
请问：
1、我刚刚下载的windows 0.2.9 版本，还是不能订阅；
2、而且打开软件“配置PROFILES”也没有默认配置；
3、左下角的版本号，为什么是“v0.2.0” ?

如图：
![Pandora-Box](https://github.com/snakem982/Pandora-Box/assets/47548777/5552d842-c611-4481-8d17-7cc0b44c1422)
![Pandora-Box2](https://github.com/snakem982/Pandora-Box/assets/47548777/da5c00b7-9cbc-44cc-a6c8-bdf64a2b1040)

**Comment by snakem982** [comment]
已经重新打包了，请去v0.2.9版本重新下载软件包
然后再打开试试

**Comment by snakem982** [comment]
首次进入配置页面打开是这个样子就正常了
<img width="922" alt="202406" src="https://github.com/snakem982/Pandora-Box/assets/127644738/7b23096f-3e89-4986-8792-c9e672245abb">

**Comment by shermans** [comment]
下0.2.9和0.2.10. 打开都是0.2.0
V2RAY和clash都正常使用的订阅
在这里都使用不了

**Comment by snakem982** [comment]
> 下0.2.9和0.2.10. 打开都是0.2.0 V2RAY和clash都正常使用的订阅 在这里都使用不了

1、配置页面截图看下
2、打开通用，打开配置目录，log.log文件脱敏上传下
<img width="873" alt="ok" src="https://github.com/snakem982/Pandora-Box/assets/127644738/622484e1-faac-47a4-a0ab-dd57ba83d5da">

**Comment by shermans** [comment]
log里面没有东西. 是不是没有文件夹读写权限导致的啊

**Comment by snakem982** [comment]
> log里面没有东西. 是不是没有文件夹读写权限导致的啊

那你用管理员权限运行试下

**Comment by shermans** [comment]
[log.log](https://github.com/user-attachments/files/15863577/log.log)
日志文件.

**Comment by snakem982** [comment]
> [log.log](https://github.com/user-attachments/files/15863577/log.log) 日志文件. 直接传的,不知道什么叫脱敏. 脱敏是隐藏我的隐私信息的意思吗? 我不知道哪些是, 反正我用的网络公开的订阅.

0.2.10 修复了一下重新打包了  再下载试试吧

**Comment by shermans** [comment]
> > [log.log](https://github.com/user-attachments/files/15863577/log.log) 日志文件. 直接传的,不知道什么叫脱敏. 脱敏是隐藏我的隐私信息的意思吗? 我不知道哪些是, 反正我用的网络公开的订阅.
> 
> 0.2.10 修复了一下重新打包了 再下载试试吧 若还有问题，麻烦再传下日志

可以了.它是不是不识别clash订阅啊. 是把v2ray的订阅放进去,它自己有内置的clash极简规则.这个倒是挺方便.
就是自带的默认配置不好,
我觉得按我朝律法,软件作者就有了"提供非法信道"的行为了.
要不然你把默认配置去掉, 以规避风险保护自己.
然后写详细一点的使用说明吧.
反正我看了半天才会有.
倒是很方便
希望能持续更新.

**Comment by shermans** [comment]
> > [log.log](https://github.com/user-attachments/files/15863577/log.log) 日志文件. 直接传的,不知道什么叫脱敏. 脱敏是隐藏我的隐私信息的意思吗? 我不知道哪些是, 反正我用的网络公开的订阅.
> 
> 0.2.10 修复了一下重新打包了 再下载试试吧 若还有问题，麻烦再传下日志

可以了.它是不是不识别clash订阅啊. 是把v2ray的订阅放进去,它自己有内置的clash极简规则.这个倒是挺方便.
就是自带的默认配置不好,
我觉得按我朝律法,软件作者就有了"提供非法信道"的行为了.
要不然你把默认配置去掉, 以规避风险保护自己.
然后写详细一点的使用说明吧.
反正我看了半天才会有.
倒是很方便
希望能持续更新.

**Comment by shermans** [comment]
> > [log.log](https://github.com/user-attachments/files/15863577/log.log) 日志文件. 直接传的,不知道什么叫脱敏. 脱敏是隐藏我的隐私信息的意思吗? 我不知道哪些是, 反正我用的网络公开的订阅.
> 
> 0.2.10 修复了一下重新打包了 再下载试试吧 若还有问题，麻烦再传下日志

可以了.它是不是不识别clash订阅啊. 是把v2ray的订阅放进去,它自己有内置的clash极简规则.这个倒是挺方便.
就是自带的默认配置不好,
我觉得按我朝律法,软件作者就有了"提供非法信道"的行为了.
要不然你把默认配置去掉, 以规避风险保护自己吧.
然后写详细一点的使用说明吧.
反正我看了半天才会用.
如果有说明手册参考,倒是很方便,我觉得已经能跟V2RAY和clash一决高下了.再发展几个月就很棒了.
希望能持续更新.并且及时支持后面出现的各种协议.

**Comment by snakem982** [comment]
1、可以识别 Clash 订阅，若解析失败，可能订阅挂了或者403拒绝访问，
因为支持批量解析，所以页面没有提示具体错误，都是解析失败  
想看具体错误可查看日志
2、默认配置不会删除，它是给抓取用的，但里面的节点后续会删除
3、使用说明嘛，懒，会用clash 用这个也是手到擒来
4、后续更新会随Mihomo内核同步更新
