### ISSUE TITLE
proxypool的四个分别是什么啊

### ISSUE THREAD

**Issue by shermans** [snakem982/Pandora-Box#13]
不好意思啊[proxypool]里面不能提问.跑这里来问.四个链接不认识都是什么
nodelist.txt是网友公开的clash或者v2ray订阅.
proxies.txt是什么啊.什么软件可以调用它们呢?还有另外两个
webfuzz.yaml
tgchannel.json

**Comment by snakem982** [comment]
自己打开里面的地址看看呗 
全靠悟 (#^.^#)
