### ISSUE TITLE
请求添加新功能：新增clash api 接口

### ISSUE THREAD

**Issue by cody33231** [snakem982/Pandora-Box#15]
请求添加新功能：新增clash api 接口，可以使用yacd界面选择节点，谢谢！

**Comment by snakem982** [comment]
预览版自行下载
https://github.com/snakem982/Pandora-Box/releases/tag/Prerelease-main

<img width="819" alt="copy clash api" src="https://github.com/user-attachments/assets/dff83f9b-86d5-4ae6-95b5-a3b40b93454b">
