### ISSUE TITLE
WIN版爬取功能无效

### ISSUE THREAD

**Issue by OP404OP** [snakem982/Pandora-Box#17]
v0.2.20 WIN版爬取功能无效，无论怎么设置都是提示爬取失败。v0.2.19爬取功能正常

**Comment by snakem982** [comment]
已修复
https://github.com/snakem982/Pandora-Box/releases/latest

**Comment by OP404OP** [comment]
> 已修复 https://github.com/snakem982/Pandora-Box/releases/latest

三克油 bro

**Comment by OP404OP** [comment]
这种符合分享链接，但是选择分享链接类型却不行，只能选择自定义输入。
看了下说明里面，分享链接类型是符合开头的。
 ss://...
 ssr://...
 vmess://...
 vless://...
 trojan://...
 tuic://...
 hysteria://...
 hysteria2://...
 hy2://...
![image](https://github.com/user-attachments/assets/4ca5d071-a86c-4ede-b894-c46b3e760d22)

**Comment by snakem982** [comment]
类型是根据响应内容来的，而不是输入内容，前几种只支持标准https/http的地址
最后一种类型，自定义输入支持网址和分享链接同时输入

**Comment by OP404OP** [comment]
> 类型是根据响应内容来的，而不是输入内容，前几种只支持标准https/http的地址 最后一种类型，自定义输入支持网址和分享链接同时输入

懂了，三克油 bro
