### ISSUE TITLE
筛选过后还是会有大量的Error节点

### ISSUE THREAD

**Issue by OP404OP** [snakem982/Pandora-Box#18]
不清楚什么导致的。因为有些被爬取的订阅地址可能会被墙或屏蔽了CN地区，需要借助一个订阅来正常获取节点信息，在想是不是因为这个导致的有些节点可能已经挂了，起码地址在CN被墙了。因为选择了个订阅，所以爬取时候订阅里的节点去测被爬取的节点导致的被爬取节点的地址是正常的，而实际上被爬取的节点在CN地区是已经挂了（clash verge）。（我瞎想的）因为要考虑到不是所有爬取都是http形式，我的话是直接丢 proxies: 里面的节点信息到自定义里面。

爬取功能没法单独开启是否启用代理。话说后续出批量测速麽

**Comment by snakem982** [comment]
1、爬取前退出其他代理软件
爬取被墙的地址需要在软件里导入一个可用的订阅
软件对于一个地址的访问，会同时通过 代理访问、直连访问 发起请求，哪个返回内容可用使用哪个

2、测试可用性的时候，不会通过代理的，是直接测试你电脑到节点的连接

3、不会出批量测速，太浪费流量了
如果爬出 1000+ 的节点 那测速得到什么时候 不好估计啊

**Comment by OP404OP** [comment]
> 1、爬取前退出其他代理软件 爬取被墙的地址需要在软件里导入一个可用的订阅 软件对于一个地址的访问，会同时通过 代理访问、直连访问 发起请求，哪个返回内容可用使用哪个
> 
> 2、测试可用性的时候，不会通过代理的，是直接测试你电脑到节点的连接
> 
> 3、不会出批量测速，太浪费流量了 如果爬出 1000+ 的节点 那测速得到什么时候 不好估计啊

好的 谢谢解答，我不懂代码所以没看源码，只是一个猜想。

批量测速的话 节点量多的话确实费时间 费流量。或许加个自定义数量，测 前10 前20 节点也不错

软件筛选限制了导出节点数量，我前几天爬了800多，因为上限512 ，丢到v2rayN里批量测速，速度也还行蛮快的。（缺点就是v2rayn没法直接用yaml的本地配置文件，只能去其他网站转换对应协议格式还要二次解码）
看了下v2rayN里的参数是超时10s 测速网址https://speed.cloudflare.com/__down?bytes=100000000

**Comment by snakem982** [comment]
支持爬取、导出v2ray配置和测速的
可使用这个项目
[proxypool](https://github.com/ssrlive/proxypool)

Pandora-Box 的爬取逻辑参阅了部分代码

**Comment by OP404OP** [comment]
> 支持爬取、导出v2ray配置和测速的 可使用这个项目 [proxypool](https://github.com/ssrlive/proxypool)
> 
> Pandora-Box 的爬取逻辑参阅了部分代码

我基本上只用clash ，找了个简单测速的脚本 也还行。
