### ISSUE TITLE
请问能否支持爬取白嫖机场节点

### ISSUE THREAD

**Issue by bywhat123** [snakem982/Pandora-Box#19]
https://github.com/wzdnzd/aggregator  大佬能不能支持自动爬取白嫖机场的节点，就像这个项目一样，能从机场列表里自动注册购买白嫖套餐

**Comment by snakem982** [comment]
Pandora-Box只支持简单的 `url` 爬取
[aggregator](https://github.com/wzdnzd/aggregator) 这个逻辑比较复杂，Pandora-Box 不会支持
若不想自己部署，可使用 [proxypool](https://github.com/snakem982/proxypool) 项目的 [clash-meta-2.yaml](https://github.com/snakem982/proxypool/blob/main/source/clash-meta-2.yaml) 文件
