### ISSUE TITLE
可否将配置文件放置在可执行文件文件夹。

### ISSUE THREAD

**Issue by winterli1** [snakem982/Pandora-Box#20]
目前是放置在用户文件夹下。

**Comment by snakem982** [comment]
这个有什么特别说法吗？
用户文件夹也可以修改执行权限的

**Comment by redfrog999** [comment]
支持这个特性啊，这样不同机器之间切换就很方便，即点即用，无需把配置文件拷到用户文件夹内。

**Comment by snakem982** [comment]
> 支持这个特性啊，这样不同机器之间切换就很方便，即点即用，无需把配置文件拷到用户文件夹内。

可以出一个打包配置文件，导入配置文件 功能
至于 app 和 配置  在一个目录  这个不考虑

**Comment by redfrog999** [comment]
> > 支持这个特性啊，这样不同机器之间切换就很方便，即点即用，无需把配置文件拷到用户文件夹内。
> 
> 可以出一个打包配置文件，导入配置文件 功能 至于 app 和 配置 在一个目录 这个不考虑

这也行啊，方便不少，期待下个版本

**Comment by winterli1** [comment]
> > 支持这个特性啊，这样不同机器之间切换就很方便，即点即用，无需把配置文件拷到用户文件夹内。
> 
> 可以出一个打包配置文件，导入配置文件 功能 至于 app 和 配置 在一个目录 这个不考虑
可以导入导出也方便很多，期待更新。

**Comment by snakem982** [comment]
预览版可用
 https://github.com/snakem982/Pandora-Box/releases/tag/Prerelease-main
