### ISSUE TITLE
系统代理设置bug

### ISSUE THREAD

**Issue by moonloadermic** [snakem982/Pandora-Box#21]
win10 ltsc 2019
Pandora-Box版本号：v0.2.24

1.设置为系统代理 system proxy 开启后，重启软件，打开系统代理界面，发现下图状况。
![bug](https://github.com/user-attachments/assets/94f1973e-e92d-4fd6-ab2e-e8a247a4e930)

还要手动把代理设置成下图才能连上。
![good](https://github.com/user-attachments/assets/560f7b29-5747-4ab3-85e4-1d5ca5667566)

2.控制面板 clash api
http://127.0.0.1:9966

chrome打开后提示：
{"message":"Unauthorized"}

**Comment by snakem982** [comment]
> 2.控制面板 clash api
> http://127.0.0.1:9966/
> 
> chrome打开后提示：
> {"message":"Unauthorized"}

这个是需要配合  https://yacd.metacubex.one/ 
来使用的
<img width="533" alt="控制面板" src="https://github.com/user-attachments/assets/ec94fe35-9fb6-4cac-a7c5-205fe570111f" />

**Comment by moonloadermic** [comment]
@snakem982 
您好，谢谢解答，两个问题都已解决💖
但是感觉系统代理都填在地址栏，能连上，但是识别速度慢。
所以请问能否能效仿其他软件（比如v2rayN，Clash Verge等）地址栏和端口分别填写？
这样感觉识别速度快，格式也好看。

**Comment by snakem982** [comment]
> 所以请问能否能效仿其他软件（比如v2rayN，Clash Verge等）地址栏和端口分别填写？
> 这样感觉识别速度快，格式也好看。

有空儿研究研究怎么设置

**Comment by moonloadermic** [comment]
@snakem982
> 有空儿研究研究怎么设置

好的，谢谢了。

**Comment by snakem982** [comment]
预览版已修改代理的设置，可提前尝鲜
https://github.com/snakem982/Pandora-Box/releases/tag/Prerelease-main

**Comment by moonloadermic** [comment]
GOOD！预览版系统代理格式整齐了💖
