### ISSUE TITLE
No Support mac ?

### ISSUE THREAD

**Issue by Romntic** [snakem982/Pandora-Box#23]
hello  
how are u ?
thanks for u hard work 
before u make apps for macOs 
can u  resupport

**Comment by snakem982** [comment]
The app supports macos.

https://github.com/snakem982/Pandora-Box/releases/latest
If it is an M processor, you can download [darwin-arm64.zip](https://github.com/snakem982/Pandora-Box/releases/download/v0.2.24/darwin-arm64.zip)
If it is an Intel processor, you can download [darwin-amd64.zip](https://github.com/snakem982/Pandora-Box/releases/download/v0.2.24/darwin-amd64.zip)

**Comment by Romntic** [comment]
**### thanks i didn't notice that**
