### ISSUE TITLE
最新版本，爬取失败

### ISSUE THREAD

**Issue by cfinle** [snakem982/Pandora-Box#24]
0.2.25 爬取失败，能否跳过爬取失败的订阅，继续爬取其他的，爬取失败的给个状态或者日志
![爬取失败](https://github.com/user-attachments/assets/d5458598-37dc-4d2e-8167-dfa9c5a13574)

**Comment by snakem982** [comment]
因为你爬取的内容需要科学上网，所以爬取前在配置里导入一个可用的订阅，不然是爬取不到内容的
日志在通用-->打开配置-->log.log可看

**Comment by cfinle** [comment]
![QQ20241222-124713](https://github.com/user-attachments/assets/9ecd465d-e7ef-47a9-bf7d-2ac6fd5f1512)
有可用的订阅，是昨天又加了好几个订阅节点，，然后就不行了
以前爬取是fuzzy，现在是auto，是否有影响？

**Comment by snakem982** [comment]
没有影响，代码做了兼容，fuzzy改成auto了  好理解些

**Comment by cfinle** [comment]
刚翻了下log文件，一开始是好几个订阅里边没有节点，所以报错，删了之后，重新抓取，是timeout，但是浏览器打开是有节点的，这个可否增加一键修改Authorization、User-Agent，增加订阅状态显示

**Comment by cfinle** [comment]
还有超时时间自己定义，感谢

**Comment by snakem982** [comment]
> 刚翻了下log文件，一开始是好几个订阅里边没有节点，所以报错，删了之后，重新抓取，是timeout，但是浏览器打开是有节点的，这个可否增加一键修改Authorization、User-Agent

软件请求一个地址，是直连和代理同时发起请求的
发现 HttpGetWithTimeout 是正常的，这个走的是直连，不经过代理的，爬取需要科学代理的地址一般报这个错
如果是 HttpGetByProxy  那说明地址是不能用了

一键修改Authorization、User-Agent 可以考虑

**Comment by snakem982** [comment]
> 增加订阅状态显示
> 还有超时时间自己定义，感谢

爬取逻辑，不是单条订阅获取到节点然后测试，是所有的订阅获取到节点后汇总测试
所以订阅状态显示加不了

超时时间自定义，这个涉及底层http请求函数修改，改动面比较大 暂时不考虑

**Comment by cfinle** [comment]
> > 增加订阅状态显示
> > 还有超时时间自己定义，感谢
> 
> 爬取逻辑，不是单条订阅获取到节点然后测试，是所有的订阅获取到节点后汇总测试 所以订阅状态无法显示
> 
> 超时时间自定义，这个涉及底层http请求函数修改，改动面比较大 暂时不考虑

1、不好意思，没说明白，我说的超时，指的是访问订阅地址超时时间。
如果超过时间，那么在这个订阅地址后边加一列，给个提示，比如红色，就知道哪个有问题，可以精准修改
2、订阅地址一键去重功能，大佬看看是否复杂
3、批量复制订阅地址进来，自动分段是否可以增加
最后，感谢提供的优秀工具，便于像我这样的小白

**Comment by snakem982** [comment]
> 1、不好意思，没说明白，我说的超时，指的是访问订阅地址超时时间。
如果超过时间，那么在这个订阅地址后边加一列，给个提示，比如红色，就知道哪个有问题，可以精准修改

超时时间无法修改，明年会考虑修改这个订阅异常显示问题，今年开发结束了，放假放假

> 2、订阅地址一键去重功能，大佬看看是否复杂
已经去重了，添加订阅的时候会检查的

> 3、批量复制订阅地址进来，自动分段是否可以增加
使用自定义，订阅，分享，yaml ，base64 随便写，已经实现了

**Comment by cfinle** [comment]
好的，元旦快乐

**Comment by snakem982** [comment]
元旦快乐
