### ISSUE TITLE
关于软件安装的问题

### ISSUE THREAD

**Issue by NuoL5623** [snakem982/Pandora-Box#4]
大佬，我试着在另外一台电脑上安装了软件，不过出现了一些问题
![1](https://github.com/snakem982/Pandora-Box/assets/125172739/2773b91f-d799-4732-80f1-1a5c1c7dd437)
![2](https://github.com/snakem982/Pandora-Box/assets/125172739/6467b7f4-6f67-4faf-a4c1-3b554c74445c)
![3](https://github.com/snakem982/Pandora-Box/assets/125172739/fd59f8fb-3c92-4693-9065-86d3dfd6652a)
![4](https://github.com/snakem982/Pandora-Box/assets/125172739/3600567a-5475-46a7-b209-78cc4601fcc6)
![5](https://github.com/snakem982/Pandora-Box/assets/125172739/e29569c1-f4f4-439f-9c7b-5b708296a61c)
下载的最新的版本，解压缩之后打开之后版本号还是显示上一个版本
配置里面也没有任何内容，尝试了本地导入和链接导入，没有任何反应
添加抓取链接也是同样没有反应呢
不知道是什么原因，希望大佬能够帮忙解答，非常感谢

**Comment by NuoL5623** [comment]
原本安装正常运行软件的电脑，重新启动之后也出现了这个问题，不知道要怎么修复呢...

**Comment by snakem982** [comment]
去任务管理里看看有没有Pandora-Box这个程序，有的话全部杀掉，再打开试试
目前软件没有单实例检测，双击软件后等一会儿直到软件加载出来，千万别多次双击

**Comment by snakem982** [comment]
抓取要先点击添加，列表里有地址才能点击抓取按钮
<img width="1177" alt="111" src="https://github.com/snakem982/Pandora-Box/assets/127644738/553fe91d-63f8-4ce1-b1ff-949e2a4e35c5">

**Comment by NuoL5623** [comment]
我胡乱捣鼓了一下，切换了网络状态之后 软件又自动恢复了...
先是切换到了手机热点--恢复了
然后又切换到路由器的2.4G的网络，也恢复了（之前连接的是路由器的5G）
现在到台式机的网线连接，我就不确定这个是怎么回事了

**Comment by snakem982** [comment]
没有默认配置选项的，就是软件开了多个实例，去任务管理结束任务就好
