### ISSUE TITLE
希望可以添加一个Tun功能

### ISSUE THREAD

**Issue by lx-xang** [snakem982/Pandora-Box#5]
首先非常感谢大佬开发的这个软件，真的很好用
  以前我的电视机网络用的是clash里面的tun模式，这样我的电视机就不需要重新去折腾了，如果这个功能添加起来比较简单那麻烦您添加一下，非常感谢！！！

**Comment by snakem982** [comment]
这个不会加哦，软件是针对小白的，打开软件能代理能用就行。
tun模式属于高级玩家，这个还是用老牌代理软件吧。
