### ISSUE TITLE
Can't set to system proxy on windows 10.  Set 127.0.0.1:52915 by manual is OK 

### ISSUE THREAD

**Issue by flexwin** [snakem982/Pandora-Box#6]

**Comment by snakem982** [comment]
### Turn this button on to automatically set the system proxy.<br>If it doesn't work, change to other software
<img width="724" alt="1111111111111" src="https://github.com/snakem982/Pandora-Box/assets/127644738/66bd9401-6bc4-4fb6-aaf0-0761626290e9">
