### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by mak589** [snakem982/Pandora-Box#8]
订阅链接无法导入！

**Comment by snakem982** [comment]
1、网络是畅通的吗？
2、页面提示什么？
3、有没有链接无法导入，报错的截图？

**Comment by mak589** [comment]
需要等很久，但是无法使用！

**Comment by mak589** [comment]
没有提示

**Comment by snakem982** [comment]
软件首次打开比较慢，再次打开就快了
如果有提示需要网络连接权限  要点击允许
配置页面是空白？能提供个截图看看吗
