### ISSUE TITLE
一直显示解析中

### ISSUE THREAD

**Issue by ichat001** [snakem982/Pandora-Box#9]
第一次使用该软件, 把下面链接中的节点链接拷贝过来后, 执行, 如下图所示, 一直显示解析, 等了半个小时也没有反应
https://github.com/snakem982/proxypool?tab=readme-ov-file

能指导一下应该怎样用吗? 全网搜索没有找到相关的视频解说或使用方法说明
系统: windows10 pro

![zz](https://github.com/snakem982/Pandora-Box/assets/166457982/8b4ddc05-71ed-479b-86a5-862e434f9bde)

**Comment by snakem982** [comment]
若第一次打开软件，配置页面显示 这样就可以正常使用了
<img width="1192" alt="12" src="https://github.com/snakem982/Pandora-Box/assets/127644738/d493794e-dd33-44ad-8651-fed4fe562efb">

**Comment by ichat001** [comment]
> 试试这样操作 退出其他代理软件，然后以管理员身份运行

感谢大佬的快速回复!
我是开了一下全局VPN, 然后导入节点, 等了一两分钟, 然后有了如下图的显示, 然后关了全局VPN, 似乎也能显示了...
但是我现在还真不知道怎么用这个软件, 我是在ghithub搜索 **hysteria free** 找到大佬的软件的,  我现在用的是免费的VPN, 是hysteria的免费节点, 但地址是法国的, 我想找到新加坡的节点来用在VPN上, 能给指点迷津吗? 万分感谢!
![Z](https://github.com/snakem982/Pandora-Box/assets/166457982/35808df6-3c8a-4489-94ce-5edcb578586e)

**Comment by snakem982** [comment]
用法跟clash 或者 clash verge是一样的  
1、配置就是加载订阅的，有订阅往里面输入就行了
2、要进行抓取 就点 抓取 进入输入要抓取的地址就行了
3、需要新加坡节点可以使用
 https://github.com/snakem982/proxypool/blob/main/proxies.txt
里的任意地址跟上  参数 c=SG 就可以了
你比如 这个地址  http://141.147.161.50:12580/clash/proxies
变为  http://141.147.161.50:12580/clash/proxies?c=SG

**Comment by ichat001** [comment]
> 用法跟clash 或者 clash verge是一样的 1、配置就是加载订阅的，有订阅往里面输入就行了 2、要进行抓取 就点 抓取 进入输入要抓取的地址就行了 3、需要新加坡节点可以使用 https://github.com/snakem982/proxypool/blob/main/proxies.txt 里的任意地址跟上 参数 c=SG 就可以了 你比如 这个地址 http://141.147.161.50:12580/clash/proxies 变为 http://141.147.161.50:12580/clash/proxies?c=SG

多谢大佬指导, 我已经加载了你上面提到的新加坡节点, 
但是我用的是hysteria.exe 它的config.json文件如下, 我发现以前每次不能用的时候, 只要更新这个文件里的信息就行了, 但是我应该改哪一条呢? 我没有用其它的, 像clash 什么的, 因为我用hysteria这个很稳定, 下面的配置是可用的, 但是IP显示的是法国
{
"server": "51.159.79.103:55396",
"protocol": "udp",
"up_mbps": 11,
"down_mbps": 55,
"http": {
"listen": "127.0.0.1:1081",
"timeout" : 250,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:1080",
"timeout": 250,
"disable_udp": false
},
"obfs": "",
"auth_str": "dongtaiwang.com",
"alpn": "h3",
"server_name": "youku.com",
"insecure": true,
"recv_window_conn": 115343360,
"recv_window": 461373440,
"disable_mtu_discovery": true,
"resolver": "https://223.5.5.5/dns-query",
"retry": 3,
"retry_interval": 3,
"quit_on_disconnect": false,
"handshake_timeout": 15,
"idle_timeout": 30,
"fast_open": true,
"hop_interval": 120
}
